import mongoose from 'mongoose';
import dotenv from 'dotenv';

dotenv.config();

const categorySchema = new mongoose.Schema({
  slug: { type: String, required: true, unique: true },
  name: { type: String, required: true },
  icon: { type: String, default: null },
  description: { type: String, default: null },
  parentSlug: { type: String, default: null },
  sortOrder: { type: Number, default: 0 },
  level: { type: Number, required: true, default: 1 },
  isLeaf: { type: Boolean, required: true, default: false },
  icon3d: { type: String, default: null },
  keywordTokens: { type: [String], default: [] },
  isOther: { type: Boolean, default: false },
  isActive: { type: Boolean, default: true },
  autoGenerated: { type: Boolean, default: false },
  visible: { type: Boolean, default: true },
}, { timestamps: true });

const Category = mongoose.models.Category || mongoose.model('Category', categorySchema);

async function ensureOtherCategory() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    const existingTopLevelOther = await Category.findOne({
      $or: [
        { slug: 'inoe', level: 1 },
        { slug: 'other', level: 1 },
        { isOther: true, level: 1 }
      ]
    });

    if (existingTopLevelOther) {
      console.log('Top-level category "Иное" already exists:', existingTopLevelOther.slug);
      
      if (!existingTopLevelOther.isOther) {
        await Category.updateOne({ _id: existingTopLevelOther._id }, { $set: { isOther: true } });
        console.log('Updated isOther flag to true');
      }
    } else {
      const newCategory = new Category({
        slug: 'inoe',
        name: 'Иное',
        description: 'Прочие товары и услуги',
        level: 1,
        isLeaf: false,
        isOther: true,
        isActive: true,
        visible: true,
        sortOrder: 999,
        icon3d: '/attached_assets/generated_images/box_3d.png',
        keywordTokens: ['другое', 'иное', 'прочее', 'разное']
      });

      await newCategory.save();
      console.log('Created new category "Иное":', newCategory.slug);
    }

    const allTopCategories = await Category.find({ level: 1, isActive: true }).select('slug name isOther');
    console.log('\nAll top-level categories:');
    allTopCategories.forEach(cat => {
      console.log(`  - ${cat.name} (${cat.slug})${cat.isOther ? ' [isOther]' : ''}`);
    });

  } catch (error) {
    console.error('Error:', error);
  } finally {
    await mongoose.disconnect();
    console.log('\nDisconnected from MongoDB');
  }
}

ensureOtherCategory();
