import express from 'express';
import AutoCategorizationService from '../../services/AutoCategorizationService.js';

const router = express.Router();

router.post('/suggest', async (req, res) => {
  try {
    const { title, description } = req.body;

    if (!title || title.trim().length < 3) {
      return res.status(400).json({
        success: false,
        error: 'Заголовок обязателен и должен быть не менее 3 символов'
      });
    }

    const result = await AutoCategorizationService.autoCategorizeAd({
      title: title.trim(),
      description: description?.trim() || ''
    });

    res.json({
      success: true,
      data: result
    });
  } catch (error) {
    console.error('[AutoCategorization API] Error:', error);
    res.status(500).json({
      success: false,
      error: 'Ошибка авто-категоризации'
    });
  }
});

router.post('/update-visibility', async (req, res) => {
  try {
    const { minAdsCount = 5 } = req.body;

    const result = await AutoCategorizationService.updateVisibilityByAdCount(minAdsCount);

    res.json({
      success: true,
      data: result
    });
  } catch (error) {
    console.error('[AutoCategorization API] Error updating visibility:', error);
    res.status(500).json({
      success: false,
      error: 'Ошибка обновления видимости'
    });
  }
});

router.get('/stats', async (req, res) => {
  try {
    const stats = await AutoCategorizationService.getAutoGeneratedStats();

    res.json({
      success: true,
      data: stats
    });
  } catch (error) {
    console.error('[AutoCategorization API] Error getting stats:', error);
    res.status(500).json({
      success: false,
      error: 'Ошибка получения статистики'
    });
  }
});

export default router;
