import mongoose from 'mongoose';

const categorySchema = new mongoose.Schema(
  {
    slug: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      lowercase: true,
    },
    name: {
      type: String,
      required: true,
      trim: true,
    },
    icon: {
      type: String,
      default: null,
    },
    description: {
      type: String,
      default: null,
    },
    parentSlug: {
      type: String,
      default: null,
      trim: true,
      index: true,
    },
    sortOrder: {
      type: Number,
      default: 0,
    },
    level: {
      type: Number,
      required: true,
      default: 1,
      index: true,
    },
    isLeaf: {
      type: Boolean,
      required: true,
      default: false,
      index: true,
    },
    icon3d: {
      type: String,
      default: null,
    },
    keywordTokens: {
      type: [String],
      default: [],
      index: true,
    },
    boostWeight: {
      type: Number,
      default: 1.0,
    },
    isOther: {
      type: Boolean,
      default: false,
      index: true,
    },
    isActive: {
      type: Boolean,
      default: true,
      index: true,
    },
    type: {
      type: String,
      enum: ['product', 'service', 'real-estate', 'vehicle', 'agro', null],
      default: null,
    },
    isFarmerCategory: {
      type: Boolean,
      default: false,
      index: true,
    },
    isSeasonal: {
      type: Boolean,
      default: false,
      index: true,
    },
    seasonStart: {
      type: Date,
      default: null,
    },
    seasonEnd: {
      type: Date,
      default: null,
    },
    unitTypes: {
      type: [String],
      enum: ['kg', 'g', 'piece', 'liter', 'pack', 'jar', 'bunch', 'bag'],
      default: [],
    },
    defaultUnit: {
      type: String,
      enum: ['kg', 'g', 'piece', 'liter', 'pack', 'jar', 'bunch', 'bag', null],
      default: null,
    },
    isDynamic: {
      type: Boolean,
      default: true,
      index: true,
    },
    dynamicMinCountLocal: {
      type: Number,
      default: 5,
    },
    dynamicMinCountCountry: {
      type: Number,
      default: 10,
    },
    autoGenerated: {
      type: Boolean,
      default: false,
      index: true,
    },
    autoGeneratedAt: {
      type: Date,
      default: null,
    },
    sourceKeywords: {
      type: [String],
      default: [],
    },
  },
  {
    timestamps: true,
  }
);

categorySchema.index({ parentSlug: 1, isOther: 1 });
categorySchema.index({ isFarmerCategory: 1, isActive: 1 });
categorySchema.index({ isSeasonal: 1, seasonStart: 1, seasonEnd: 1 });

export default mongoose.model('Category', categorySchema);
